# DATA samples
# This is UL2016 preVFP (APV) / HIPM
singlemu:
  - [
      /SingleMuon/Run2016B-HIPM_UL2016_NanoAODv15_v2-v1/NANOAOD,
      /SingleMuon/Run2016B-HIPM_UL2016_NanoAODv15-v1/NANOAOD,
      /SingleMuon/Run2016C-HIPM_UL2016_NanoAODv15-v1/NANOAOD,
      /SingleMuon/Run2016D-HIPM_UL2016_NanoAODv15-v1/NANOAOD,
      /SingleMuon/Run2016E-HIPM_UL2016_NanoAODv15-v1/NANOAOD,
      /SingleMuon/Run2016F-HIPM_UL2016_NanoAODv15-v1/NANOAOD,
    ]
