[workspace]
authors = ["Jan-Frederik Schulte <jschulte@cern.ch>"]
channels = ["conda-forge", "nvidia"]
name = "ScoutingVVVTools"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.*"
pandas = ">=3.0.3,<4"
numpy = ">=2.4.6,<3"
uproot = ">=5.7.4,<6"
matplotlib = ">=3.11.0,<4"
mplhep = ">=1.2.0,<2"
py-xgboost-gpu = ">=2.1.4,<4"


[feature.gpu]
system-requirements = { cuda = "12" }

[feature.gpu.dependencies]
py-xgboost-gpu = "*"

[environments]
gpu = { features = ["gpu"] }
