[workspace]
authors = ["Jan-Frederik Schulte <jschulte@cern.ch>"]
channels = ["conda-forge"]
name = "ScoutingVVVTools"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
pileup = "./run.sh 1"
convert = "./run.sh 0"
mix = "./run.sh 6"
train = "./run.sh 2"
scale-factor-ntuple = "python3 run.py 11"
scale-factor-fit = "python3 run.py 12"

[dependencies]
python = "3.11.*"
pandas = ">=2.2,<3"
numpy = ">=1.26,<3"
uproot = ">=5.6,<6"
matplotlib = ">=3.8,<4"
mplhep = ">=1.2.0,<2"
xgboost = ">=2,<4"
pyyaml = ">=6,<7"
awkward = ">=2.6,<3"
coffea = ">=2024.1.0,<2027"
hist = ">=2.7,<3"
boost-histogram = ">=1.4,<2"
correctionlib = ">=2.6,<3"
scipy = ">=1.11,<2"
numba = ">=0.59,<1"
seaborn = ">=0.13,<0.14"
tqdm = ">=4.67.0,<5"
yaml-cpp = ">=0.8.0,<0.9"
