# Stored FatJet tagger names for muon-channel NanoAOD v15 runtime cards.
stored_tagger_names:
  - globalParT3_QCD
  - globalParT3_TopbWev
  - globalParT3_TopbWmv
  - globalParT3_TopbWq
  - globalParT3_TopbWqq
  - globalParT3_TopbWtauhv
  - globalParT3_WvsQCD
  - globalParT3_XWW3q
  - globalParT3_XWW4q
  - globalParT3_XWWqqev
  - globalParT3_XWWqqmv
  - globalParT3_Xbb
  - globalParT3_Xcc
  - globalParT3_Xcs
  - globalParT3_Xqq
  - globalParT3_Xtauhtaue
  - globalParT3_Xtauhtauh
  - globalParT3_Xtauhtaum
  - globalParT3_massCorrGeneric
  - globalParT3_massCorrX2p
  - globalParT3_withMassTopvsQCD
  - globalParT3_withMassWvsQCD
  - globalParT3_withMassZvsQCD
  - particleNetLegacy_QCD
  - particleNetLegacy_Xbb
  - particleNetLegacy_Xcc
  - particleNetLegacy_Xqq
  - particleNetLegacy_mass
  - particleNetWithMass_H4qvsQCD
  - particleNetWithMass_HbbvsQCD
  - particleNetWithMass_HccvsQCD
  - particleNetWithMass_QCD
  - particleNetWithMass_TvsQCD
  - particleNetWithMass_WvsQCD
  - particleNetWithMass_ZvsQCD
  - particleNet_QCD
  - particleNet_QCD0HF
  - particleNet_QCD1HF
  - particleNet_QCD2HF
  - particleNet_WVsQCD
  - particleNet_XbbVsQCD
  - particleNet_XccVsQCD
  - particleNet_XggVsQCD
  - particleNet_XqqVsQCD
  - particleNet_XteVsQCD
  - particleNet_XtmVsQCD
  - particleNet_XttVsQCD
  - particleNet_massCorr
